### ISSUE TITLE
Issue on milestone-5 PR

### ISSUE THREAD

**Issue by spydaspider** [AbigiyaTY/Portofolio-#8]
- [ ] The design looks good. Not many changes are required.
- [ ] The link opens correctly to the website and the site layout is properly structured according to the template you choose. Good job! hugs
- [ ]  The readme file looks professional.
  - No linter errors were observed which is excellent!
  -  You used the appropriate GitHub Flow
     Happy coding!!
